### ISSUE TITLE
Do not use RMS, it's not the RMS.

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/dragonboard_testbench#15]
Please, call it standard deviation:

https://en.wikipedia.org/wiki/Root_mean_square
https://en.wikipedia.org/wiki/Standard_deviation

FYI: the root of all evil:

https://root.cern.ch/root/html534/src/TH1.cxx.html#tv3dGD
>   Note that this function returns the Standard Deviation (Sigma)
  of the distribution (not RMS).

**Comment by dneise** [comment]
Can you point out where this was violated .. 
I didn't stumble over it so far.
