### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/dragonboard_testbench#19]
Dear developers,

What is the file format for input ?
How and where can I download one ?

Thank you, Jean

**Comment by dneise** [comment]
Hey Jean,

The files themselves are not open to the public at the moment. We got a few files for RnD directly from the dragon team in Japan. Currently we are waiting for more files ourselves. 

One [example file](https://github.com/cta-observatory/dragonboard_testbench/blob/master/fake_pedestal.dat) however is available in this repository, so if you cloned it, you got it already :-)

Some documents regarding the file format were given to us directly from Daisuke Nakajima, and I must admit I have no idea whether we may publish them here or not... I also have no idea if those documents can be found somewhere on the CTA document servers.

What are you currently trying to do, if I may ask? Maybe we can share data via some non public link...

**Comment by jacquemier** [comment]
Thanks,

For the time being, I just want to test and see how it works.
