### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by dneise** [cta-observatory/dragonboard_testbench#23]
`RunningStats` is pure math and therefore nicely decoupled and nicely testable. 
I think it needs to be unit tested quickly.

Maybe this is a nice opportunity for people who have never written a unit test and would learn how this works... 

The example below is one thing that should work but does not. 

~~~
In [1]: import numpy as np

In [2]: from dragonboard.runningstats import RunningStats

In [3]: x = np.arange(1000).reshape(500, 2)

In [4]: rs = RunningStats(x[0].shape)

In [5]: for i in x:
    rs.add(i)
   ...:    

In [6]: rs.mean
Out[6]: array([ 499.,  500.])

In [7]: rs.std
Out[7]: array([ nan,  nan])
~~~

**Comment by dneise** [comment]
If you'd like to read up about Python unit testing, maybe this is a nice starting point:

 * http://docs.python-guide.org/en/latest/writing/tests/

**Comment by Froehliche-Kernschmelze** [comment]
That*s cool stuff. Will get around to this in the future.

**Comment by MaxNoe** [comment]
We should use py.test, as this is used by ctapipe.

There is an introduction on unit testing for cta here:
https://github.com/cta-observatory/training-material/blob/master/tutorials/UnitTests.ipynb

**Comment by MaxNoe** [comment]
I implemented two first unit tests in #25, we can add more. 
I will see that we also start using travis for this project.

**Comment by MaxNoe** [comment]
Travis is now running: https://travis-ci.org/cta-observatory/dragonboard_testbench

**Comment by MaxNoe** [comment]
We also need unit tests for everything else, we e. g. use the dummy files to test the reading and offset calculation.

**Comment by MaxNoe** [comment]
I close this, as the ci is setup and first tests there.
