### ISSUE TITLE
offset_calculation.py parallel?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/dragonboard_testbench#24]
When executing `offset_calculation.py` I see that it uses a single core, which is at 100% load. This means it is not slow, because the disk cannot deliver the data faster, but it is slow because it needs more processing power ... 

So I was wondering if one can write it in a way so it uses more cores on my machine. I tried `multiprocessing` but I cannot get it to work... so I give it up for now.

Maybe somebody else is interested? Please assign yourself.

**Comment by dneise** [comment]
Okay I got it ... together with some "improvements" here and there I was able to reduce runtime from ~15min to ~1.5min ... 

However, this comes at a price ... the code becomes less readable (well this might be possible to improve a little bit, by choosing better names here and there...) and longer.

I am not sure at all, if we like this, but I wanted to test how much I can achieve. 

Would be happy, if you had a look at the stuff .. maybe we want a part of it...

**Comment by dneise** [comment]
https://github.com/cta-observatory/dragonboard_testbench/tree/performace_improvement

**Comment by MaxNoe** [comment]
We said, we should not be concerned to much with performance right now.
