### ISSUE TITLE
time-lapse correction

### ISSUE THREAD

**Issue by dneise** [cta-observatory/dragonboard_testbench#27]
As shown by Julian Sitarek in his [Analysis techniques and performance of the Domino Ring Sampler version 4 based readout for the MAGIC telescopes](http://arxiv.org/abs/1305.1007) 
in Figure 3 (see below), the DRS4 shows a certain offset dependent on the time between consecutive events. 

![figure3](https://cloud.githubusercontent.com/assets/8200858/14099554/e2b405d2-f586-11e5-9fbe-ce13168fe7f6.jpg)

We **assume** the same offset to be present also in data recorded by the dragonboard and plan to correct for this offset later on. As a first step we must show: This time-dependent baseline shift (shorter but still clear name is urgently needed!) is present, i.e. we can measure it. The second step, the correction, is then simple. 

---

In order to show this effect or to measure it, we can use pedestal events which were recorded with different time periods between each other. Recently new data was given to us. This data was triggered with a pseudo random trigger, leading to varying times between consecutive events. The mean rate of the random trigger was set to 1kHz and 10kHz. 

First we need to ensure, the time between events is really not fixed, otherwise any further study would be futile. The following picture shows the time between consecutive events for one of the files given to us.
![time_between_events_for_example_file](https://cloud.githubusercontent.com/assets/8200858/14099914/c7e97c20-f589-11e5-9edd-b79fab940c11.png)

The average time difference seems to be at 1kHz, which makes sense looking at the file name.
The distribution of the triggers resembles an exponential distribution with a cut off below 1ms. The exponential distribution means, the triggers are not only randomly distributed, but mimic a natural poisson distribution. This is not important for this study but never the less a cool feature.

----

Due to the different file formats, the `event.header` has changed. The new header contains several counters:
 * `pps_counter` (pps : pulse per second, this is a GPS name.)
 * `counter_10MHz`
 * `counter_133MHz`

I found, that `counter_10MHz` and `pps_counter` in this example file were always zero. So I used `counter_133MHz` to calculate the time between consecutive events.

----

So the plot was made like this:

~~~
import os
import dragonboard as db
import numpy as np
import matplotlib.pyplot as plt
plt.ion()

path = '../raw_data_20160229/20160229_185742_ExtTrgRand/Ped_Rand1kHz_No1_IP90.dat'
times = []
for event in db.EventGenerator(path):
    times.append(event.header.counter_133MHz / 133e6)
times = np.array(times)
delta_t_in_ms = np.diff(times)*1e3
print(delta_t_in_ms.mean())

plt.hist(delta_t_in_ms, bins=100, histtype="step")
plt.xlabel("time between consecutive events / ms")
plt.title(os.path.basename(path))
~~~

----

The goal of this study would be to show that we can measure the baseline shift shown in figure 3 of the paper cited above also for the new dragonboard data. Once we have that, we should define new tasks.

**Comment by Froehliche-Kernschmelze** [comment]
Perfect, exactly what I wanted to get to. I'll be at it and keep all up to date in this issue.

**Comment by Froehliche-Kernschmelze** [comment]
Here are the histograms of all the other files. thought it might be useful that we can be sure about a poisson distribution

![hist_1khz_1_ip90](https://cloud.githubusercontent.com/assets/16683448/14177814/587c8ff0-f758-11e5-9926-7510599ef174.png)
![hist_1khz_2_ip90](https://cloud.githubusercontent.com/assets/16683448/14177813/5879cd10-f758-11e5-82ee-460b899b6dba.png)
![hist_1khz_3_ip90](https://cloud.githubusercontent.com/assets/16683448/14177815/58805496-f758-11e5-8938-d5e50d763a80.png)
![hist_1khz_4_ip90](https://cloud.githubusercontent.com/assets/16683448/14177817/588750ac-f758-11e5-87f1-0725aeeb122c.png)
![hist_1khz_6_ip90](https://cloud.githubusercontent.com/assets/16683448/14177816/5883e5b6-f758-11e5-97ad-77b23a951207.png)
![hist_1khz_7_ip90](https://cloud.githubusercontent.com/assets/16683448/14177818/5889db7e-f758-11e5-8160-c40377d80982.png)
![hist_1khz_8_ip90](https://cloud.githubusercontent.com/assets/16683448/14177819/5898272e-f758-11e5-9118-e13f351f3dc8.png)
![hist_10khz_1_ip90](https://cloud.githubusercontent.com/assets/16683448/14177821/589ba610-f758-11e5-96fd-2f0a53bbffa4.png)
![hist_10khz_2_ip90](https://cloud.githubusercontent.com/assets/16683448/14177820/589935ec-f758-11e5-96ea-9a6b10f7ddc0.png)
![hist_10khz_3_ip90](https://cloud.githubusercontent.com/assets/16683448/14177822/589c0b8c-f758-11e5-8f46-c3fa4e169933.png)
![hist_10khz_4_ip90](https://cloud.githubusercontent.com/assets/16683448/14177823/58a1358a-f758-11e5-8cdd-d80c1173e6b7.png)
![hist_10khz_5_ip90](https://cloud.githubusercontent.com/assets/16683448/14177824/58a99194-f758-11e5-91c3-506a3e4ce02d.png)
![hist_10khz_6_ip90](https://cloud.githubusercontent.com/assets/16683448/14177825/58b2c912-f758-11e5-953e-d5368834210a.png)
![hist_10khz_7_ip90](https://cloud.githubusercontent.com/assets/16683448/14177826/58b5ecc8-f758-11e5-9faa-2fe5f908d41d.png)
![hist_10khz_8_ip90](https://cloud.githubusercontent.com/assets/16683448/14177827/58b65ae6-f758-11e5-9017-ca9edd0bb6a3.png)

**Comment by MaxNoe** [comment]
I will close this for now as this is basically implemented and under evaluation.
