### ISSUE TITLE
Provide inputfiles instead of inputfolder

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/dragonboard_testbench#29]
I think it would be better to let the shell handle the inputfiles instead of using `glob.glob` on an inputfolder.

Using docopt one could achieve this using:

```
Usage:
  offset_calculation.py [options] <inputfile> ... 
```

Then it is possible to use calls like:

```
offset_calculation.py folder1/*.dat folder2/*.dat
```

or
```
offset_calculation.py *No1*.dat
```

**Comment by dneise** [comment]
I think we can close this, no?

**Comment by MaxNoe** [comment]
yes
